/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/edit/$id': typeof EditIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/edit/$id': typeof EditIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/edit/$id': typeof EditIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$slug': typeof RecipeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/edit/$id'
    | '/profile/$username'
    | '/recipe/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/edit/$id'
    | '/profile/$username'
    | '/recipe/$slug'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/edit/$id'
    | '/profile/$username'
    | '/recipe/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  EditIdRoute: typeof EditIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RecipeSlugRoute: typeof RecipeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  EditIdRoute: EditIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RecipeSlugRoute: RecipeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
